version: '3.8'

services:
  web:
    container_name: inno_frontend_web
    image: nginx:stable
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
    ports:
      - "80:80"
    networks:
      - inno_app_network

  node:
    container_name: inno_frontend_node
    image: node:20
    environment:
      NODE_ENV: dev
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: sh -c "yarn install && yarn build"
#    stdin_open: true
    networks:
      - inno_app_network
volumes:
  build:
networks:
  inno_app_network:
    driver: bridge

