version: '3.8'

services:
  web:
    container_name: inno_backend_app
    image: webdevops/php-apache-dev:8.2
    environment:
      WEB_DOCUMENT_ROOT: /var/www/public
    volumes:
      - .:/var/www
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    working_dir: /var/www
    ports:
      - "88:80"
    networks:
        - inno_app_network
  db:
    container_name: inno_backend_db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass
      - MYSQL_USER=local
      - MYSQL_DATABASE=local
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
        - inno_app_network
volumes:
  mysql-data:
networks:
  inno_app_network:
    driver: bridge
